### ISSUE TITLE
Stop before red

### ISSUE THREAD

**Issue by psnx** [psnx/CarND-Capstone#8]
We need to implement a proper stop procedure each time a red light is detected.
I would propose that we make a deceleration curve for each such case, and feed the actual target speed to the speed controller depending on our distance to the traffic light and speed.
`planned_v = get_target_speed_deceleration(wp_stop, actual_v, car_position)`

**Comment by toby-coleman** [comment]
We also should include a couple of parameters:
* If distance to the red light is less `min_dist` metres *when it is initially detected* then we should ignore it;
* If the last red light was detected more than `timeout` seconds ago we should assume the light has turned green and start moving again.

The target speed planner should be able to plan deceleration to zero when a red traffic light is seen and acceleration to target speed when the way ahead is clear.

**Comment by psnx** [comment]
Partly implemented, help is sought! see the new file `speed_envelope.py`

**Comment by psnx** [comment]
Case closed for 1st submission
