### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by toby-coleman** [psnx/CarND-Capstone#9]
Once we've completed the remaining code we will need to test the finished system both on the simulator and with the real-world ros bag file, and finalise all the settings before submission for Udacity review.

Thoughts:
* May need to test on a GPU machine or AWS instance to get it to run fast enough.  Currently not sure how complex this is to achieve.

**Comment by renlei1982** [comment]
Agree. The simulator on my computer is very slow even if I turned off the light detection.
